repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
    - name: falco
      namespace: falco
      chart: stable/falco
      version: 1.0.9
      wait: true
      timeout: 100
      atomic: true
      values:
        - "../config/default/falco.yaml"
