# Default values for plugins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


backend:
  replicaCount: 1
  image:
    repository: jenkinsciinfra/plugin-site-api
    tag: 133-b6e652
    pullPolicy: IfNotPresent
  port: 8080
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi

frontend:
  replicaCount: 1
  image:
    repository: halkeye/gatsby
    tag: disable-open-fd
    pullPolicy: Always
  port: 80
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP

# Please define ingress settings into environment variable
ingress:
  enabled: false
  paths:
    - path: /api/(.*)
      port: backend
    - path: /(.*)
      port: frontend

#  annotations:
#    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
#    "kubernetes.io/ingress.class": "public-ingress"
#    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
#
#  hosts:
#    - host: plugins.jenkins.io
#
#  tls:
#    - secretName: plugins-tls
#      hosts:
#        - plugins.jenkins.io


nodeSelector: {}

tolerations: []

affinity: {}

dataFileUrl: https://ci.jenkins.io/job/Infra/job/plugin-site-api/job/generate-data/lastSuccessfulBuild/artifact/plugins.json.gzip
restApiUrl: https://plugins.jenkins.io/api

github:
  clientId: ""
  clientSecret: ""

# the volume to mount
# e.g.
# htmlVolume:
#   hostPath:
#     path: /host
htmlVolume:

# name of the azure storage account to be used
azureStorageAccountName:
# key for accessing the azure storage account
azureStorageAccountKey:
